### ISSUE TITLE
mailprotector_textblock doesn't work on RichText blocks from StreamBlock

### ISSUE THREAD

**Issue by UDAR-TomH** [bnzk/django-mailprotector#13]
Trying to apply mailprotector_textblock to a RichText block yields a "object of type 'RichText' has no len()" error.

Using the following code:
```
{% for block in page.body %}
        <div class="block-{{ block.block_type }}">
            {% mailprotector_textblock block.value as protected_block %}
            {{ protected_block }}
        </div>
{% endfor %}
```

**Comment by benzkji** [comment]
On a first glance, I don't see any len() calls in mailprotector's code. Could you provide a complete stack trace? I am not familiar with wagtail and it's RichText, but would say that the rendered .value should be able to provide a length?

**Comment by UDAR-TomH** [comment]
My apologies, I have found a solution. I needed to use block.value.source to get the actual text content of the RichTextBlock. I will delete this ticket.

**Comment by benzkji** [comment]
no problem :)
